# Szablon hiperparametrów per-dataset.
# Po kalibracji cross-dataset zaktualizuj poniższe wartości i zamroź.
selectors:
  frfs:
  elastic_net:
    l1_ratio: 0.5
    C: 0.5
    max_iter: 15000
    tol: 1.0e-2
  rf:
    n_estimators: 300
    max_depth: null
    min_samples_leaf: 1
    n_jobs: -1
  xgb:
    n_estimators: 300
    max_depth: 6
    subsample: 0.8
    colsample_bytree: 0.8
    learning_rate: 0.1
    eval_metric: logloss
    n_jobs: -1

models:
  random_forest:
    n_estimators: 400
    max_depth: null
    min_samples_leaf: 1
    n_jobs: -1
  xgboost:
    n_estimators: 500
    learning_rate: 0.1
    max_depth: 6
    subsample: 0.9
    colsample_bytree: 0.9
    eval_metric: logloss
    n_jobs: -1
    tree_method: hist
  svm:
    kernel: linear
    C: 1.0
    probability: true
  logistic_regression:
    max_iter: 1500
    C: 1.0
