# Szablon hiperparametrów per-dataset.
# Po kalibracji cross-dataset zaktualizuj poniższe wartości i zamroź.
selectors:
  frfs: 
    max_samples: 1200
    dtype: float32
  elastic_net:
    l1_ratio: 0.5
    C: 0.5
    max_iter: 10000
    tol: 0.001
  rf_fs:
    n_estimators: 200
    max_depth: null
    min_samples_leaf: 1
    n_jobs: -1
  xgb_fs:
    n_estimators: 300
    max_depth: 6
    subsample: 0.8
    colsample_bytree: 0.8
    learning_rate: 0.1
    eval_metric: logloss
    n_jobs: -1
models:
  random_forest:
    n_estimators: 300
    max_depth: null
    min_samples_leaf: 1
    n_jobs: -1
  xgboost:
    n_estimators: 400
    learning_rate: 0.1
    max_depth: 6
    subsample: 0.9
    colsample_bytree: 0.9
    eval_metric: logloss
    n_jobs: -1
  svm:
    kernel: linear
    C: 1.0
    probability: true
  logistic_regression:
    max_iter: 1000
    C: 1.0