dataset: "musk_v2"
target_column: "target"

# CV
k_folds: 5
feature_counts: [20, 50]

# siatka eksperymentu
noise_levels: [0.0, 0.1, 0.25, 0.5, 1.0]
binning_methods: ["none", "static", "quantile", "kmeans"]
feature_methods: ["frfs", "elastic_net", "rf", "xgb"]
classifiers: ["random_forest", "xgboost", "svm", "logistic_regression"]

# hiperparametry
hparams_dir: "hparams"

# strumieniowanie wyników (opcjonalne – dopisywane w trakcie)
stream_summary_csv: "results/musk_v2_stream_summary.csv"

# zapis końcowy
output_csv: "results/musk_v2_summary.csv"
